# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python
variables:
  CONDA_ENV_PATH: /usr/share/miniconda/envs/omigami/
  CONDA_CACHE_DIR: $(Pipeline.Workspace)/.condarc

trigger:
- master
pool:
  vmImage: ubuntu-latest
strategy:
  matrix:
    Python37:
      python.version: '3.7'
    Python38:
      python.version: '3.8'

steps:
  - checkout: self
    fetchDepth: 1
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: 'Add conda to PATH'

  - task: Cache@2
    inputs:
      key: 'python | "$(Agent.OS)" | requirements/environment.frozen.yaml | requirements/environment_test.yaml'
      restoreKeys: |
        python | "$(Agent.OS)"
        python
#      path: $(CONDA_CACHE_DIR)
      path: $(CONDA_ENV_PATH)
      cacheHitVar: CACHE_RESTORED
    displayName: 'Cache Conda packages'

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
    displayName: 'Use Python $(python.version)'

  - bash: |
      conda env create -f requirements/environment.frozen.yaml
      conda activate omigami
      conda env update -f requirements/environment_test.yaml
    displayName: 'Create Anaconda environment'
    condition: eq(variables.CACHE_RESTORED, 'false')

  - bash: |
      source activate omigami
      pip install pytest pytest-azurepipelines==1.0.0rc5
      pytest \
        --junitxml=junit/test-results-quick.xml \
        --cov=spec2vec_mlops \
        --cov-report=xml \
        --cov-report=html \
        spec2vec_mlops
    displayName: 'Run all tests'

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: '**/test-*.xml'
      testRunTitle: 'Publish test results for Omigami'
  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
      reportDirectory: '$(System.DefaultWorkingDirectory)/**/htmlcov'