variables:
  CONDA_CACHE_DIR: $(Pipeline.Workspace)/.condarc

trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo "##vso[task.prependpath]$CONDA/bin"
  displayName: Add conda to PATH

- task: Cache@2
  displayName: Use cached Anaconda environment
  inputs:
    key: 'conda | "$(Agent.OS)" | environment.yml'
    restoreKeys: | 
      python | "$(Agent.OS)"
      python
    path: $(CONDA_CACHE_DIR)
    cacheHitVar: CONDA_CACHE_RESTORED

- script: |
    conda env create --quiet --file requirements/environment.frozen.yaml
    conda env update --quiet --file requirements/environment_test.yaml
  displayName: Create Anaconda environment
  condition: eq(variables.CONDA_CACHE_RESTORED, 'false')