prefect:
  project: "spec2vec"
storage:
  documents:
    dev: "s3://omigami-dev/spec2vec/documents"
    prod: "s3://omigami/spec2vec/documents"
  model_folder:
    dev: "s3://omigami-dev/spec2vec/mlflow"
    prod: "s3://omigami/spec2vec/mlflow"
  redis:
    spectrum_id_sorted_set: "spectrum_id_precursor_mz_sorted"
    spectrum_hashes: "spectrum_data"
    document_hashes: "document_data"
    embedding_hashes: "embedding_data"
    env_vars:
      redis_host: "REDIS_HOST"
      redis_db: "REDIS_DB"