prefect:
  project: "spec2vec"
storage:
  documents:
    positive: "documents/positive"
    negative: "documents/negative"
  redis:
    spectrum_id_sorted_set: "spectrum_id_precursor_mz_sorted"
    spectrum_hashes: "spectrum_data"
    document_hashes: "document_data"
    embedding_hashes: "embedding_data"
    env_vars:
      redis_host: "REDIS_HOST"
      redis_db: "REDIS_DB"