apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: DUMMY_NAME
  namespace: seldon
spec:
  name: DUMMY_NAME
  annotations:
    seldon.io/rest-timeout: "600000"
    seldon.io/grpc-timeout: "600000"
  predictors:
  - graph:
      children: []
      implementation: MLFLOW_SERVER
      modelUri: dummy
      name: spec2vec
    name: default
    replicas: 1
    traffic: 100
    componentSpecs:
    - spec:
        # We are setting high failureThreshold as installing conda dependencies
        # can take long time and we want to avoid k8s killing the container prematurely
        initContainers:
          - image: gcr.io/kfserving/storage-initializer:v0.4.0
            imagePullPolicy: IfNotPresent
            name: spec2vec-model-initializer
        containers:
        - name: spec2vec
          resources:
            requests:
              memory: 2Gi
          readinessProbe:
            failureThreshold: 10
            initialDelaySeconds: 120
            periodSeconds: 30
            successThreshold: 1
            tcpSocket:
              port: 9000
            timeoutSeconds: 3
          livenessProbe:
            failureThreshold: 10
            initialDelaySeconds: 120
            periodSeconds: 30
            successThreshold: 1
            tcpSocket:
              port: 9000
            timeoutSeconds: 3
          env:
            - name: REDIS_HOST
              value: "redis-master.redis"
            - name: OMIGAMIDIR
              value: "/mnt/models/code/omigami"
