name: omigami
channels:
  - conda-forge
  - bioconda
  - nlesc
dependencies:
  - spec2vec=0.4.*
  - numpy=1.19.*
  - pandas=1.2.*
  - ijson=3.1.*
  - python-kubernetes=12.0.*
  - pyyaml=5.4.*
  - pip
  - pip:
      - matchms==0.8.*
      - mlflow==1.14.*
      - redis==3.5.*
      - seldon-core==1.6.*
