name: omigami
channels:
  - conda-forge
  - bioconda
  - nlesc
dependencies:
  - spec2vec=0.4.0
  - numpy=1.19.2
  - pandas=1.2.3
  - ijson=3.1.3
  - python-kubernetes=12.0.1
  - pyyaml=5.4.1
  - pip
  - pip:
      - matchms==0.8.2
      - mlflow==1.14.1
      - redis==3.5.3
      - seldon-core==1.6.0

