name: omigami
channels:
  - conda-forge
  - bioconda
  - nlesc
dependencies:
  - rdkit=2020.09.5
  - pip
  - pip:
      - ms2deepscore==0.2.1
      - matchmsextras==0.2.3
      - pubchempy==1.0.2
      - tensorflow==2.5.0
