storage:
  model_folder:
    dev:
      pre-trained-model: "s3://omigami-dev/ms2deepscore/model/pre-trained/ms2deep_score.hdf5"
      mlflow: "s3://omigami-dev/ms2deepscore/mlflow/"
    prod:
      pre-trained-model: "s3://omigami/ms2deepscore/model/pre-trained/ms2deep_score.hdf5"
      mlflow: "s3://omigami/ms2deepscore/mlflow/"