

model_uri: "https://zenodo.org/api/files/2ca8a77b-fa1e-4223-bc6d-50d6f074a962/MS2DeepScore_allGNPSpositive_10k_500_500_200.hdf5"

storage:
  model_folder:
    dev:
      pre_trained_model: "model/pre_trained/{date:%Y-%m}"
    prod:
      pre_trained_model: "model/pre_trained/{date:%Y-%m}"
