name: omigami
channels:
  - conda-forge
  - bioconda
  - nlesc
dependencies:
  - python=3.7
  - pip
  - prefect=0.14.*
  - confuse=1.4.*
  - rdkit=2020.09.*
  - click=7.1.*
  - pip:
      - tensorflow==2.5.0
      - ms2deepscore==0.2.*
      - git+https://github.com/datarevenue-berlin/drfs
      - matchmsextras==0.2.*
      - pubchempy==1.0.*
