name: spec2vec_mlops
channels:
  - conda-forge
  - bioconda
  - nlesc
dependencies:
  - python=3.7
  - pip
  - prefect=0.14.12
  - confuse=1.4.0
  - spec2vec=0.4.0
  - rdkit=2020.09.5
  - click=7.1.2
  - boto3=1.17.27
  - ijson=3.1.3
  - numpy=1.19.2
  - pandas=1.2.3
  - python-kubernetes=12.0.1
  - s3fs=0.4.2
  - pyyaml=5.4.1
  - pip:
      - matchms==0.8.2
      - redis==3.5.3
      - mlflow==1.14.1
      - seldon-core==1.6.0
      - git+https://github.com/datarevenue-berlin/drfs
