name: spec2vec_mlops
channels:
  - conda-forge
  - bioconda
  - nlesc
dependencies:
  - python=3.7
  - pip
  - prefect=0.14.*
  - confuse=1.4.*
  - spec2vec=0.4.*
  - rdkit=2020.09.*
  - click=7.1.*
  - boto3=1.17.*
  - ijson=3.1.*
  - numpy=1.19.*
  - pandas=1.2.*
 - pyyaml=5.4.*
  - pip:
      - matchms==0.8.*
      - feast==0.9.*
      - mlflow==1.14.*
      - seldon-core==1.7.*
