name: spec2vec_mlops
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.8
  - pip
  - prefect=0.14.12
  - pip:
      - ijson==3.1.4
      - git+https://github.com/datarevenue-berlin/drfs
