name: omigami
channels:
  - conda-forge
  - bioconda
  - nlesc
dependencies:
  - python=3.7
  - pip
  - prefect=0.14.12
  - confuse=1.4.0
  - rdkit=2020.09.5
  - click=7.1.2
  - pip:
      - tensorflow==2.5.0
      - ms2deepscore==0.2.1
      - git+https://github.com/datarevenue-berlin/drfs
      - matchmsextras==0.2.3
      - pubchempy==1.0.2
