name: omigami
channels:
  - conda-forge
  - bioconda
  - nlesc
dependencies:
  - python=3.7
  - pip
  - prefect=0.14.12
  - confuse=1.4.0
  - click=7.1.2
  - pip:
      - git+https://github.com/datarevenue-berlin/drfs
