name: omigami
channels:
  - conda-forge
  - bioconda
  - nlesc
dependencies:
  - black=20.8b1
  - boto3=1.17.27
  - s3fs=0.4.2
  - pip
  - pip:
      - pytest-pycharm
      - pytest-redis
      - moto==2.2.15
      - requests-mock==1.8.0
      - pytest==3.8.2
      - pytest-runner==4.2
      - pytest-cov==2.7.1
      - pytest-azurepipelines
      - kubetest==0.9.5
