name: omigami
channels:
  - conda-forge
  - bioconda
  - nlesc
dependencies:
  - python=3.7
  - pip
  - prefect=0.14.*
  - confuse=1.4.*
  - click=7.1.*
  - pip:
      - git+https://github.com/datarevenue-berlin/drfs
