name: spec2vec_mlops
channels:
  - conda-forge
  - bioconda
  - nlesc
dependencies:
  - python=3.7
  - pip
  - prefect=0.14.*
  - confuse=1.4.*
  - spec2vec=0.4.*
  - rdkit=2020.09.*
  - ijson=3.1.*
  - click=7.1.*
  - boto3=1.17.*
  - pip:
      - git+https://github.com/datarevenue-berlin/drfs
      - matchms==0.8.*
      - feast==0.9.*