name: omigami
channels:
  - conda-forge
  - bioconda
  - nlesc
dependencies:
  - python=3.7
  - pip
  - prefect=0.14.*
  - confuse=1.4.*
  - spec2vec=0.4.*
  - rdkit=2020.09.*
  - click=7.1.*
  - boto3=1.17.*
  - ijson=3.1.*
  - numpy=1.19.*
  - pandas=1.2.*
  - python-kubernetes=12.0.*
  - s3fs=0.4.*
  - pyyaml=5.4.*
  - pip:
      - tensorflow==2.5.0
      - matchms==0.8.*
      - ms2deepscore==0.2.*
      - redis==3.5.*
      - mlflow==1.14.*
      - seldon-core==1.6.*
      - git+https://github.com/datarevenue-berlin/drfs
      - matchmsextras==0.2.*
      - pubchempy==1.0.*
