name: spec2vec_mlops
channels:
  - conda-forge
  - bioconda
  - nlesc
dependencies:
  - python=3.7
  - pip
  - prefect=0.14.12
  - confuse=1.4.0
  - spec2vec=0.4.0
  - rdkit=2020.09.5
  - ijson==3.1.3
  - pip:
      - git+https://github.com/datarevenue-berlin/drfs
      - matchms==0.8.2