name: spec2vec_mlops
channels:
  - conda-forge
  - bioconda
  - nlesc
dependencies:
  - pytest
  - pytest-cov
  - black=20.8b1
  - pyspark=3.0.1
  - pip
  - pip:
      - pytest-pycharm
      - moto==1.3.16
      - requests-mock==1.8.0
