name: spec2vec_mlops
channels:
  - conda-forge
  - bioconda
  - nlesc
dependencies:
  - python=3.7
  - pip
  - prefect=0.14.12
  - confuse=1.4.0
  - spec2vec=0.4.0
  - rdkit=2020.09.5
  - click=7.1.2
  - boto3=1.17.27
  - ijson=3.1.3
  - pip:
      - matchms==0.8.2
      - feast==0.9.3
      - mlflow==1.14.1
