gnps_uri:
  complete: "https://gnps-external.ucsd.edu/gnpslibrary/ALL_GNPS.json"
  partial: "https://raw.githubusercontent.com/MLOps-architecture/share/main/test_data/SMALL_GNPS.json"
prefect:
  project: "spec2vec"
  api_server:
    prod: "https://prefect.omigami.datarevenue.com/graphql"
    dev: "https://prefect.mlops.datarevenue.com/graphql"
mlflow: "http://mlflow.mlflow:5000"
seldon:
  group: "machinelearning.seldon.io"
  version: "v1alpha2"
  plural: "seldondeployments"
  namespace: "seldon"
storage:
  dataset_dir:
    dev:
      small: "downloaded_datasets/small"
      10k: "downloaded_datasets/10k"
      full: "downloaded_datasets/full"
    prod: "downloaded_datasets"
  model_folder:
    dev: "s3://omigami-dev/spec2vec/mlflow"
    prod: "s3://omigami/spec2vec/mlflow"
  s3_bucket:
    dev: "s3://omigami-dev"
    prod: "s3://omigami"
  redis:
    spectrum_id_sorted_set: "spectrum_id_precursor_mz_sorted"
    spectrum_hashes: "spectrum_data"
    document_hashes: "document_data"
    embedding_hashes: "embedding_data"
clusters:
  dev: "dev"
  prod: "prod"