prefect:
  api_server:
    prod: "https://prefect.omigami.datarevenue.com/graphql"
    dev: "https://prefect.mlops.datarevenue.com/graphql"

mlflow: "http://mlflow.mlflow:5000"

seldon:
  group: "machinelearning.seldon.io"
  version: "v1alpha2"
  plural: "seldondeployments"
  namespace: "seldon"

storage:
  dataset_dir:
    dev:
      small: "datasets/small"
      10k: "datasets/10k"
      complete: "datasets/complete/{date:%Y-%m}"
    prod:
      complete: "datasets/complete/{date:%Y-%m}"
  s3_bucket:
    dev: "s3://omigami-dev"
    prod: "s3://omigami"

clusters:
  dev: "dev"
  prod: "prod"

login:
  prod:
    auth_url: "url"
    username: "user"
    password: "pw"
    token: "token"
  dev:
    auth_url: "url"
    username: "user"
    password: "pw"
    token: "token"


spec2vec:
  gnps_uri:
    complete: "https://gnps-external.ucsd.edu/gnpslibrary/ALL_GNPS.json"
    partial: "https://raw.githubusercontent.com/MLOps-architecture/share/main/test_data/SMALL_GNPS.json"
  storage:
    dataset_dir:
      dev:
        small: "datasets/small"
        10k: "datasets/10k"
        complete: "datasets/complete/{date:%Y-%m}"
      prod:
        complete: "datasets/complete/{date:%Y-%m}"
    model_folder:
      dev: "s3://omigami-dev/spec2vec/mlflow"
      prod: "s3://omigami/spec2vec/mlflow"
    redis:
      spectrum_id_sorted_set: "spectrum_id_precursor_mz_sorted"
      spectrum_hashes: "spectrum_data"
      document_hashes: "document_data"
      embedding_hashes: "embedding_data"

gnps_uri:
  complete: "https://gnps-external.ucsd.edu/gnpslibrary/ALL_GNPS.json"
  partial: "https://raw.githubusercontent.com/MLOps-architecture/share/main/test_data/SMALL_GNPS.json"
  partial_500_spectra: "https://raw.githubusercontent.com/MLOps-architecture/share/main/test_data/SMALL_GNPS_500_spectra.json"