prefect:
  api_server:
    prod: "https://prefect.omigami.datarevenue.com/graphql"
    dev: "https://prefect.mlops.datarevenue.com/graphql"
    local: "http://localhost:4200/graphql"

mlflow: "http://mlflow.mlflow:5000"

seldon:
  group: "machinelearning.seldon.io"
  version: "v1alpha2"
  plural: "seldondeployments"
  namespace: "seldon"

storage:
  dataset_id:
    small: "small"
    10k: "10k"
    complete: "complete/{date:%Y-%m}"
  root:
    dev: "s3://omigami-dev"
    prod: "s3://omigami"

clusters:
  local: ""
  dev: "dev"
  prod: "prod"

login:
  prod:
    auth_url: "url"
    username: "user"
    password: "pw"
    session_token: "token"
  dev:
    auth_url: "url"
    username: "user"
    password: "pw"
    session_token: "token"

gnps_uri:
  complete: "https://gnps-external.ucsd.edu/gnpslibrary/ALL_GNPS.json"
  partial: "https://raw.githubusercontent.com/MLOps-architecture/share/main/test_data/SMALL_GNPS.json"
  partial_500_spectra: "https://raw.githubusercontent.com/MLOps-architecture/share/main/test_data/SMALL_GNPS_500_spectra.json"