prefect:
  project: "spec2vec"
  api_server:
    prod: "https://prefect.omigami.datarevenue.com/graphql"
    dev: "https://prefect.mlops.datarevenue.com/graphql"

mlflow: "http://mlflow.mlflow:5000"

seldon:
  group: "machinelearning.seldon.io"
  version: "v1alpha2"
  plural: "seldondeployments"
  namespace: "seldon"

storage:
  s3_bucket:
    dev: "s3://omigami-dev"
    prod: "s3://omigami"

clusters:
  dev: "dev"
  prod: "prod"

login:
  prod:
    auth_url: "url"
    username: "user"
    password: "pw"
    token: "token"
  dev:
    auth_url: "url"
    username: "user"
    password: "pw"
    token: "token"
