mlflow: "http://mlflow.mlflow:5000"

seldon:
  group: "machinelearning.seldon.io"
  version: "v1alpha2"
  plural: "seldondeployments"
  namespace: "seldon"

storage:
  dataset_id:
    small: "small"
    small_500: "small_500"
    10k: "10k"
    complete: "complete/{date:%Y-%m}"
  redis:
    embedding_hashes: "embedding_data"
    spectrum_id_sorted_set: "spectrum_id_precursor_mz_sorted"
    spectrum_hashes: "spectrum_data"

login:
  prod:
    auth_url: "url"
    username: "user"
    password: "pw"
    session_token: "token"
  dev:
    auth_url: "url"
    username: "user"
    password: "pw"
    session_token: "token"
