name: omigami
channels:
  - conda-forge
  - bioconda
  - nlesc
dependencies:
  - python=3.7
  - pip
  - prefect=0.14.12
  - confuse=1.4.0
  - spec2vec=0.4.0
  - rdkit=2020.09.5
  - click=7.1.2
  - ijson=3.1.3
  - numpy=1.19.2
  - pandas=1.2.3
  - python-kubernetes=12.0.1
  - pyyaml=5.4.1
  - matchms=0.8.2
  - black=20.8b1
  - s3fs=0.4.2
  - boto3=1.17.27
  - pip:
      - tensorflow==2.5.0
      - ms2deepscore==0.2.1
      - redis==3.5.3
      - mlflow==1.14.1
      - seldon-core==1.12.0
      - git+https://github.com/datarevenue-berlin/drfs
      - matchmsextras==0.2.3
      - pubchempy==1.0.2
      - py_muvr==1.0.1
      - pytest-pycharm
      - pytest-redis
      - moto==2.2.15
      - requests-mock==1.8.0
      - pytest==3.8.2
      - pytest-runner==4.2
      - pytest-cov==2.7.1
      - pytest-azurepipelines
      - kubetest==0.9.5
