from spec2vec_mlops.tasks.download_data import DownloadData
from spec2vec_mlops.tasks.check_condition import check_condition
from spec2vec_mlops.tasks.process_spectrum import ProcessSpectrum
from spec2vec_mlops.tasks.seldom.deploy_model import deploy_model_task
from spec2vec_mlops.tasks.make_embeddings import make_embeddings_task
from spec2vec_mlops.tasks.register_model import register_model_task
from spec2vec_mlops.tasks.train_model import train_model_task
