from spec2vec_mlops.tasks.download_data import DownloadData
from spec2vec_mlops.tasks.process_spectrum import ProcessSpectrum
from spec2vec_mlops.tasks.seldon import DeployModelTask
from spec2vec_mlops.tasks.make_embeddings import MakeEmbeddings
from spec2vec_mlops.tasks.register_model import register_model_task
from spec2vec_mlops.tasks.train_model import TrainModel
