from spec2vec_mlops.tasks.download_data import DownloadData
from spec2vec_mlops.tasks.check_condition import check_condition
from spec2vec_mlops.tasks.process_spectrum import ProcessSpectrum
from spec2vec_mlops.tasks.seldon import DeployModel
from spec2vec_mlops.tasks.make_embeddings import MakeEmbeddings
from spec2vec_mlops.tasks.register_model import RegisterModel
from spec2vec_mlops.tasks.train_model import train_model_task
