gnps_json:
  uri: "https://gnps-external.ucsd.edu/gnpslibrary/ALL_GNPS.json"
  necessary_keys:
    - "spectrum_id"
    - "source_file"
    - "task"
    - "scan"
    - "ms_level"
    - "library_membership"
    - "spectrum_status"
    - "peaks_json"
    - "splash"
    - "submit_user"
    - "Compound_Name"
    - "Ion_Source"
    - "Compound_Source"
    - "Instrument"
    - "PI"
    - "Data_Collector"
    - "Adduct"
    - "Scan"
    - "Precursor_MZ"
    - "ExactMass"
    - "Charge"
    - "CAS_Number"
    - "Pubmed_ID"
    - "Smiles"
    - "INCHI"
    - "INCHI_AUX"
    - "Library_Class"
    - "SpectrumID"
    - "Ion_Mode"
    - "create_time"
    - "task_id"
    - "user_id"
    - "InChIKey_smiles"
    - "InChIKey_inchi"
    - "Formula_smiles"
    - "Formula_inchi"
    - "url"
cleaned_data:
  necessary_keys:
    - "source_file"
    - "task"
    - "scan"
    - "ms_level"
    - "library_membership"
    - "spectrum_status"
    - "splash"
    - "submit_user"
    - "compound_name"
    - "ion_source"
    - "compound_source"
    - "instrument"
    - "pi"
    - "data_collector"
    - "adduct"
    - "scan"
    - "precursor_mz"
    - "exactmass"
    - "charge"
    - "cas_Number"
    - "pubmed_id"
    - "smiles"
    - "inchi"
    - "inchiaux"
    - "library_class"
    - "spectrumid"
    - "ionmode"
    - "task_id"
    - "user_id"
    - "inchikey_smiles"
    - "inchikey_inchi"
    - "formula_smiles"
    - "formula_inchi"
    - "url"
feast:
  url: "0.0.0.0:6565"