gnps_json:
  uri:
    complete: "https://gnps-external.ucsd.edu/gnpslibrary/ALL_GNPS.json"
    partial: "https://raw.githubusercontent.com/MLOps-architecture/share/main/test_data/SMALL_GNPS.json"
  necessary_keys:
    - "spectrum_id"
    - "source_file"
    - "task"
    - "scan"
    - "ms_level"
    - "library_membership"
    - "spectrum_status"
    - "peaks_json"
    - "splash"
    - "submit_user"
    - "Compound_Name"
    - "Ion_Source"
    - "Compound_Source"
    - "Instrument"
    - "PI"
    - "Data_Collector"
    - "Adduct"
    - "Scan"
    - "Precursor_MZ"
    - "ExactMass"
    - "Charge"
    - "CAS_Number"
    - "Pubmed_ID"
    - "Smiles"
    - "INCHI"
    - "INCHI_AUX"
    - "Library_Class"
    - "SpectrumID"
    - "Ion_Mode"
    - "create_time"
    - "task_id"
    - "user_id"
    - "InChIKey_smiles"
    - "InChIKey_inchi"
    - "Formula_smiles"
    - "Formula_inchi"
    - "url"
cleaned_data:
  necessary_keys:
    - "compound_name"
    - "adduct"
    - "precursor_mz"
    - "charge"
    - "smiles"
    - "inchi"
    - "inchiaux"
    - "ionmode"
    - "inchikey"
    - "inchikey_smiles"
    - "inchikey_inchi"
    - "formula_smiles"
    - "formula_inchi"
feast:
  url:
    remote: "feast-feast-core.feast:6565"
    local: "0.0.0.0:6565"
  serving_url:
    remote: "feast-feast-online-serving.feast:6566"
    local: "0.0.0.0:6566"
  spark:
    base_source_location: "file:///tmp/base_source"
    output_location: "file:///tmp/output.parquet"
    output_read_location: "/tmp/output.parquet"
prefect_flow_registration:
  api_server:
    remote: "https://prefect.mlops.datarevenue.com/graphql"
    local: "http://localhost:4200"
mlflow:
  url:
    remote: "http://mlflow.mlflow:5000"
k8s:
  custom_seldon_resource:
    group: "machinelearning.seldon.io"
    version: "v1alpha2"
    plural: "seldondeployments"
    namespace: "seldon"
