apiVersion: batch/v1
kind: Job
spec:
  template:
    metadata:
      annotations:
        "cluster-autoscaler.kubernetes.io/safe-to-evict": "false"
    spec:
      containers:
      - name: flow
        resources:
          requests:
            cpu: 4
            memory: 24G
