apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: spec2vec
  namespace: seldon
spec:
  name: spec2vec
  predictors:
  - graph:
      children: []
      implementation: MLFLOW_SERVER
      modelUri: dummy
      name: spec2vec
    name: default
    replicas: 1
    traffic: 100
    componentSpecs:
    - spec:
        # We are setting high failureThreshold as installing conda dependencies
        # can take long time and we want to avoid k8s killing the container prematurely
        containers:
          - name: spec2vec
            readinessProbe:
              failureThreshold: 10
              initialDelaySeconds: 120
              periodSeconds: 30
              successThreshold: 1
              tcpSocket:
                port: 9000
              timeoutSeconds: 3
            livenessProbe:
              failureThreshold: 10
              initialDelaySeconds: 120
              periodSeconds: 30
              successThreshold: 1
              tcpSocket:
                port: 9000
              timeoutSeconds: 3
            env:
              - name: REDIS_HOST
                value: "redis-master.redis"
              - name: REDIS_DB
                value: "0"
